services:
  mongodb:
    image: mongo:7
    volumes:
      - modintel_mongo_data:/data/db
    networks:
      - modintel-net
    ports:
      - "127.0.0.1:27017:27017"
    restart: always

  proxy-waf:
    image: ghcr.io/coreruleset/coraza-crs:caddy-alpine
    volumes:
      - ./proxy-waf/Caddyfile:/config/caddy/Caddyfile
      - ./proxy-waf/coraza.conf:/opt/coraza/config.d/user.conf
      - ./proxy-waf/custom_rules.conf:/opt/coraza/config.d/custom.conf
      - ./dashboard:/srv/dashboard:ro
      - modintel_waf-logs:/var/log/coraza
    environment:
      - BACKEND=juice-shop:3000
      - CORAZA_AUDIT_LOG=/var/log/coraza/audit.json
      - PARANOIA=4
      - BLOCKING_PARANOIA=4
      - ANOMALY_INBOUND=3
    networks:
      - modintel-net
    ports:
      - "8080:8080"
      - "3000:3000"
    restart: always
    user: root

  juice-shop:
    image: bkimminich/juice-shop:latest
    networks:
      - modintel-net
    restart: always

  log-collector:
    build: ./services/log-collector
    volumes:
      - modintel_waf-logs:/var/log/coraza:ro
    environment:
      - LOG_FILE_PATH=/var/log/coraza/audit.json
      - MONGO_URI=mongodb://mongodb:27017/modintel
      - INFERENCE_ENGINE_URL=http://inference-engine:8083
    networks:
      - modintel-net
    ports:
      - "8081:8081"
    restart: always

  inference-engine:
    build: ./services/inference-engine
    ports:
      - "8083:8083"
    volumes:
      - ./models:/app/models:ro
    environment:
      - MODEL_VERSION=v3
    mem_limit: 512m
    restart: always
    networks:
      - modintel-net

  review-api:
    build: ./services/review-api
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/modintel
      - WAF_ENGINE=Coraza (Caddy edge)
      - BACKEND_TARGET=juice-shop:3000
      - INFERENCE_ENGINE_URL=http://inference-engine:8083
    networks:
      - modintel-net
    restart: always

networks:
  modintel-net:
    name: modintel_net

volumes:
  modintel_waf-logs:
    name: modintel_waf-logs
  modintel_mongo_data:
    name: modintel_mongo_data
