SecRuleEngine On

SecRequestBodyAccess On
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072

SecResponseBodyAccess On
SecResponseBodyLimit 524288

SecAuditEngine On
SecAuditLogFormat JSON
SecAuditLogType Serial
SecAuditLog /var/log/coraza/audit.json
SecAuditLogParts ABIJDEFHZ
