name: docker-build-publish

permissions:
  contents: read

on:
  push:
    branches: [modintel-base]
  pull_request:
    branches: [modintel-base]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v4

      - name: log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v6
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push log collector
        uses: docker/build-push-action@v7
        with:
          context: ./services/log-collector
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/log-collector:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: build and push inference engine
        uses: docker/build-push-action@v7
        with:
          context: ./services/inference-engine
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/inference-engine:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: build and push review api
        uses: docker/build-push-action@v7
        with:
          context: ./services/review-api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/review-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
